import { PDFDocument, StandardFonts, rgb, type PDFPage, type PDFFont } from "pdf-lib";

/**
 * Minimal PDF generation.
 *
 * docGen previously wrote `Buffer.from(JSON.stringify(...))` to a `.pdf` key —
 * every "invoice" and "contract" download was raw JSON. pdf-lib is pure JS (no
 * headless browser, no native deps) and enough for the plain business documents
 * we produce: a header, key/value metadata, line-item tables, and body text.
 */

/**
 * The standard-14 fonts use WinAnsi (CP1252); pdf-lib throws on any character
 * outside it. Real data (client names, clause JSON) can carry anything, so map
 * the common offenders and drop the rest rather than crash the doc worker.
 */
function ansi(s: string): string {
  return s
    .replace(/₹/g, "Rs")
    .replace(/[‘’‚]/g, "'")
    .replace(/[“”„]/g, '"')
    .replace(/[–—]/g, "-")
    .replace(/…/g, "...")
    .replace(/ /g, " ")
    .replace(/[^\x09\x0a\x0d\x20-\x7e¡-ÿ€•]/g, "?");
}

const MARGIN = 56;
const PAGE_W = 595.28; // A4 pt
const PAGE_H = 841.89;
const INK = rgb(0.1, 0.1, 0.12);
const MUTED = rgb(0.42, 0.42, 0.46);
const RULE = rgb(0.82, 0.82, 0.85);

export interface DocRow {
  label: string;
  value: string;
}
export interface DocLineItem {
  desc: string;
  amount: string;
}
export interface DocSpec {
  title: string;
  subtitle?: string;
  reference: string;
  meta: DocRow[];
  lineItems?: DocLineItem[];
  total?: DocLineItem;
  /** Free-form paragraphs (contract clauses, notes). */
  body?: string[];
  footer?: string;
}

class Cursor {
  page: PDFPage;
  y: number;
  constructor(
    private doc: PDFDocument,
    private font: PDFFont,
    private bold: PDFFont,
  ) {
    this.page = doc.addPage([PAGE_W, PAGE_H]);
    this.y = PAGE_H - MARGIN;
  }
  private ensure(space: number) {
    if (this.y - space < MARGIN) {
      this.page = this.doc.addPage([PAGE_W, PAGE_H]);
      this.y = PAGE_H - MARGIN;
    }
  }
  gap(h: number) {
    this.y -= h;
  }
  text(s: string, size = 10, opts: { bold?: boolean; color?: typeof INK; x?: number } = {}) {
    s = ansi(s);
    this.ensure(size + 4);
    this.y -= size;
    this.page.drawText(s, {
      x: opts.x ?? MARGIN,
      y: this.y,
      size,
      font: opts.bold ? this.bold : this.font,
      color: opts.color ?? INK,
    });
    this.y -= 4;
  }
  /** Wraps a long string to the content width. */
  paragraph(s: string, size = 10) {
    const maxW = PAGE_W - MARGIN * 2;
    const words = ansi(s).split(/\s+/);
    let line = "";
    for (const w of words) {
      const test = line ? `${line} ${w}` : w;
      if (this.font.widthOfTextAtSize(test, size) > maxW && line) {
        this.text(line, size);
        line = w;
      } else {
        line = test;
      }
    }
    if (line) this.text(line, size);
  }
  rule() {
    this.ensure(10);
    this.y -= 6;
    this.page.drawLine({
      start: { x: MARGIN, y: this.y },
      end: { x: PAGE_W - MARGIN, y: this.y },
      thickness: 0.75,
      color: RULE,
    });
    this.y -= 6;
  }
  row(label: string, value: string, size = 10) {
    label = ansi(label);
    value = ansi(value);
    this.ensure(size + 4);
    this.y -= size;
    this.page.drawText(label, { x: MARGIN, y: this.y, size, font: this.font, color: MUTED });
    const vw = this.bold.widthOfTextAtSize(value, size);
    this.page.drawText(value, {
      x: PAGE_W - MARGIN - vw,
      y: this.y,
      size,
      font: this.bold,
      color: INK,
    });
    this.y -= 4;
  }
}

export async function renderDocument(spec: DocSpec): Promise<Buffer> {
  const doc = await PDFDocument.create();
  doc.setTitle(`${spec.title} ${spec.reference}`.trim());
  doc.setProducer("StackFox");
  doc.setCreationDate(new Date());

  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const c = new Cursor(doc, font, bold);

  c.text("StackFox", 16, { bold: true });
  c.text(spec.title, 20, { bold: true });
  if (spec.subtitle) c.text(spec.subtitle, 11, { color: MUTED });
  c.text(spec.reference, 10, { color: MUTED });
  c.rule();

  for (const m of spec.meta) c.row(m.label, m.value);

  if (spec.lineItems?.length) {
    c.gap(8);
    c.text("Line items", 11, { bold: true });
    c.rule();
    for (const li of spec.lineItems) c.row(li.desc, li.amount);
    if (spec.total) {
      c.rule();
      c.row(spec.total.desc, spec.total.amount, 12);
    }
  }

  if (spec.body?.length) {
    c.gap(10);
    for (const para of spec.body) {
      c.paragraph(para);
      c.gap(4);
    }
  }

  c.gap(16);
  c.text(
    spec.footer ?? `Generated by StackFox on ${new Date().toISOString().slice(0, 10)}`,
    8,
    { color: MUTED },
  );

  const bytes = await doc.save();
  return Buffer.from(bytes);
}

/**
 * paise -> "Rs 1,23,456.00" (Indian digit grouping).
 *
 * Uses the ASCII "Rs" rather than the ₹ glyph: the PDF uses the standard
 * Helvetica font (WinAnsi encoding), which cannot encode U+20B9, and embedding
 * a Unicode font for one symbol is not worth the weight.
 */
export function inr(paise: number): string {
  const rupees = (paise / 100).toFixed(2);
  const [whole, frac] = rupees.split(".");
  const neg = whole.startsWith("-");
  const digits = neg ? whole.slice(1) : whole;
  const last3 = digits.slice(-3);
  const rest = digits.slice(0, -3);
  const grouped = rest ? rest.replace(/\B(?=(\d{2})+(?!\d))/g, ",") + "," + last3 : last3;
  return `${neg ? "-" : ""}Rs ${grouped}.${frac}`;
}
