export const EVENT_CODES = {
  // Workspace & Builder
  WORKSPACE_CREATED: "WORKSPACE_CREATED",
  WORKSPACE_UPDATED: "WORKSPACE_UPDATED",
  WORKSPACE_SERVICE_ADDED: "WORKSPACE_SERVICE_ADDED",
  WORKSPACE_SERVICE_REMOVED: "WORKSPACE_SERVICE_REMOVED",
  WORKSPACE_FEATURE_TOGGLED: "WORKSPACE_FEATURE_TOGGLED",
  WORKSPACE_CUSTOM_LINE_ADDED: "WORKSPACE_CUSTOM_LINE_ADDED",
  WORKSPACE_SE_REVIEW_REQUESTED: "WORKSPACE_SE_REVIEW_REQUESTED",
  WORKSPACE_SE_APPROVED: "WORKSPACE_SE_APPROVED",
  WORKSPACE_SE_RETURNED: "WORKSPACE_SE_RETURNED",

  // Estimate
  ESTIMATE_GENERATED: "ESTIMATE_GENERATED",
  ESTIMATE_LOCKED: "ESTIMATE_LOCKED",
  ESTIMATE_EXPIRED: "ESTIMATE_EXPIRED",
  ESTIMATE_CONVERTED: "ESTIMATE_CONVERTED",

  // Order
  ORDER_PLACED: "ORDER_PLACED",
  ORDER_ACCEPTED: "ORDER_ACCEPTED",
  ORDER_REJECTED: "ORDER_REJECTED",
  ORDER_CANCELLED: "ORDER_CANCELLED",

  // Contract
  CONTRACT_DRAFTED: "CONTRACT_DRAFTED",
  CONTRACT_CLIENT_SIGNED: "CONTRACT_CLIENT_SIGNED",
  CONTRACT_EXECUTED: "CONTRACT_EXECUTED",
  CONTRACT_AMENDED: "CONTRACT_AMENDED",
  CONTRACT_TERMINATED: "CONTRACT_TERMINATED",

  // Engagement
  ENGAGEMENT_CREATED: "ENGAGEMENT_CREATED",
  ENGAGEMENT_ACTIVATED: "ENGAGEMENT_ACTIVATED",
  ENGAGEMENT_PAUSED: "ENGAGEMENT_PAUSED",
  ENGAGEMENT_COMPLETED: "ENGAGEMENT_COMPLETED",
  ENGAGEMENT_TERMINATED: "ENGAGEMENT_TERMINATED",

  // Project
  PROJECT_CREATED: "PROJECT_CREATED",
  PROJECT_KICKED_OFF: "PROJECT_KICKED_OFF",
  PROJECT_PAUSED: "PROJECT_PAUSED",
  PROJECT_COMPLETED: "PROJECT_COMPLETED",
  PROJECT_CANCELLED: "PROJECT_CANCELLED",

  // Milestone
  MILESTONE_STARTED: "MILESTONE_STARTED",
  MILESTONE_SUBMITTED: "MILESTONE_SUBMITTED",
  MILESTONE_APPROVED: "MILESTONE_APPROVED",
  MILESTONE_REVISION_REQUESTED: "MILESTONE_REVISION_REQUESTED",

  // Change Request
  CR_SUBMITTED: "CR_SUBMITTED",
  CR_ASSESSED: "CR_ASSESSED",
  CR_APPROVED: "CR_APPROVED",
  CR_REJECTED: "CR_REJECTED",
  CR_PAID: "CR_PAID",

  // Ticket
  TICKET_OPENED: "TICKET_OPENED",
  TICKET_ACKNOWLEDGED: "TICKET_ACKNOWLEDGED",
  TICKET_RESOLVED: "TICKET_RESOLVED",
  TICKET_ESCALATED: "TICKET_ESCALATED",
  TICKET_CLOSED: "TICKET_CLOSED",

  // Invoice
  INVOICE_CREATED: "INVOICE_CREATED",
  INVOICE_SENT: "INVOICE_SENT",
  INVOICE_PAID: "INVOICE_PAID",
  INVOICE_OVERDUE: "INVOICE_OVERDUE",
  INVOICE_CANCELLED: "INVOICE_CANCELLED",

  // Payment
  PAYMENT_RECEIVED: "PAYMENT_RECEIVED",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  PAYMENT_REFUNDED: "PAYMENT_REFUNDED",

  // Webhook
  WEBHOOK_DELIVERED: "WEBHOOK_DELIVERED",
  WEBHOOK_FAILED: "WEBHOOK_FAILED",
} as const;

export type EventCode = (typeof EVENT_CODES)[keyof typeof EVENT_CODES];

export interface DomainEvent {
  code: EventCode;
  payload: Record<string, unknown>;
  actor: string;
  projectId?: string;
  engagementId?: string;
  programId?: string;
  createdAt: Date;
}
